FROM node:20-alpine

WORKDIR /app

COPY package.json .

RUN npm i

COPY . .

RUN npm run build-docker-local

CMD ["npm", "run", "start-docker-local"] #¡ May have replaced this in the "docker-compose.yml". Don't modify this CMD, if you  want flexibility, change it in the "docker-compose.yml" so that you can change the command without having to rebuild the image.

# CMD ["npm", "run", "dev-docker-local"]