export const authCheckPath = '/users/auth-check'
export const createUserPath = '/users/create'
export const loginUserPath = '/users/login'
export const getUserFileListPath = '/files/list'
export const uploadFilePath = '/files/upload'
export const deleteFilePath = '/files/delete'