import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ToastContainerClient from "../shared_components/toast_container_client";
import Navbar from "../shared_components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "OhMyCloud",
  description: "Generated by create next app",
};



  //$  Next will inject the client's currently loaded page in `children`
  //! Avoid using "<Home>" directly since it will always be loaded.
export default function RootLayout({ children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="h-[100vh] flex flex-col bg-[#1b1b1b]">
          <Navbar></Navbar>
          {children}
        </div>
        <ToastContainerClient />
      </body>
    </html>
  );
}
