FROM python:3.12-slim


WORKDIR /app

COPY requirements.txt .

# RUN "python -m venv .venv && source .venv/bin/activate" #$ This image creates a container that is itself the virtual environment. `pip` is configured to install packages under /usr/local/lib/python3.12/site-packages.

RUN pip install -r requirements.txt

COPY . .



#¡ May have replaced this in the "docker-compose.yml". Don't modify this CMD, if you  want flexibility, change it in the "docker-compose.yml" so that you can change the command without having to rebuild the image.
CMD ["python3", "src/main.py"]   